### ISSUE TITLE
[@nuxt/image] Unexpected response IPX Error (500) when running in Github Actions

### ISSUE THREAD

**Issue by jacobmolby** [nuxt/image#624]
![image](https://user-images.githubusercontent.com/25974867/193680918-72230ff3-38e6-49d7-8672-1a3cc2e83105.png)

When running our action to generate and deploy our static site, we get the error above. It only happens in Github Actions, locally (on multiple different machines) it works.

An example usage of an image is 
```html
<nuxt-img
  src="/images/my-img.png"
  alt="Image"
  format="webp"
  width="1200"
  quality="100"
  loading="lazy"
  />
```

The nuxt config looks like this:
```javascript
export default {
	ssr: true,
	target: 'static',
	buildModules: ['@nuxt/postcss8', 'nuxt-facebook-pixel-module', '@nuxt/image'],
        image: {
		        provider: 'static',
	        },
        // rest omitted...
```

The command we're running is `nuxt generate`

In https://github.com/nuxt/image/issues/250 he seemed to get the same error and it had something todo with the images not being on the file system? I tried to check that in the Action runner via `tree` unix command and they all appear to be there under `./static/images/etc.png`.

We've tried both version 0.7.1 and 0.6.2. Both resulted in the same error.

The version of nuxt is 2.15.8

Any help would be greatly appreciated!

**Comment by surgiie** [comment]
Im looking for help on this issue as well, it's causing some of our CI pipelines to continue without failure? Even when running with `nuxt --fail-on-error`  :confused:

**Comment by jacobmolby** [comment]
We figured it out. 

We had cached our `node_modules` in the Action. However we hadn't included the OS in the cache key. So I imagine the issue was that the Sharp version wasn't installed with linux binaries.

Our current step looks like this:
```
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
```
